"""added published_at to book model

Revision ID: 2feebe4cc73c
Revises: b1a78c4f9c9d
Create Date: 2025-09-04 08:45:31.850029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2feebe4cc73c'
down_revision = 'b1a78c4f9c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
