"""added book_type to book model

Revision ID: a402ac2dfb27
Revises: 2feebe4cc73c
Create Date: 2025-09-04 09:03:19.312239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a402ac2dfb27'
down_revision = '2feebe4cc73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('book_type')

    # ### end Alembic commands ###
